# Generated by Django 4.1.7 on 2023-04-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_gendertype_is_deleted_profilepicture_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendertype',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
