# Generated by Django 4.1.7 on 2023-04-10 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_gendertype_updated_at_profilepicture_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'verbose_name_plural': 'users'},
        ),
    ]
