# Generated by Django 4.1.7 on 2023-04-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gendertype',
            options={'default_related_name': 'genders', 'ordering': ['name'], 'permissions': (('can_view_gender', 'Can view gender'), ('can_add_gender', 'Can add gender'), ('can_edit_gender', 'Can edit gender'), ('can_delete_gender', 'Can delete gender')), 'verbose_name': 'gender', 'verbose_name_plural': 'genders'},
        ),
        migrations.AlterModelOptions(
            name='profilepicture',
            options={'default_related_name': 'profile_pictures', 'ordering': ['-date_created'], 'verbose_name': 'profile picture', 'verbose_name_plural': 'profile pictures'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'default_related_name': 'users', 'ordering': ['email'], 'permissions': (('can_view_user', 'Can view user'), ('can_add_user', 'Can add user'), ('can_edit_user', 'Can edit user'), ('can_delete_user', 'Can delete user')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddIndex(
            model_name='gendertype',
            index=models.Index(fields=['id', 'name'], name='users_gende_id_8e980a_idx'),
        ),
        migrations.AddIndex(
            model_name='profilepicture',
            index=models.Index(fields=['id'], name='users_profi_id_5fbb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id', 'phone_number'], name='users_user_id_f03e9e_idx'),
        ),
    ]
