# Generated by Django 4.1.7 on 2023-04-08 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('theme', '0001_initial'),
        ('currencies', '0002_alter_currency_options'),
        ('payment_methods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0002_usersetting_delete_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.currency'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_methods.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.theme'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
