# Generated by Django 4.1.7 on 2023-04-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='categories__id_cdcfb9_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['id', 'parent'], name='categories__id_0e871a_idx'),
        ),
    ]
