# Generated by Django 4.1.7 on 2023-04-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_categories__id_cdcfb9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='related_categories',
            field=models.ManyToManyField(null=True, to='categories.category'),
        ),
    ]
