# Generated by Django 4.1.7 on 2023-04-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_related_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
