# Generated by Django 4.1.7 on 2023-04-21 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('categories', '0005_alter_category_related_categories'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='categories__id_0e871a_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.business'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['id', 'name', 'parent'], name='categories__id_cc83f7_idx'),
        ),
    ]
