# Generated by Django 4.1.7 on 2023-04-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'default_related_name': 'themes', 'ordering': ['-created_at'], 'permissions': (('can_view_theme', 'Can view theme'), ('can_add_theme', 'Can add theme'), ('can_edit_theme', 'Can edit theme'), ('can_delete_theme', 'Can delete theme')), 'verbose_name': 'theme', 'verbose_name_plural': 'themes'},
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['id'], name='theme_theme_id_d90744_idx'),
        ),
    ]
