# Generated by Django 4.1.7 on 2023-04-10 08:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('stock_quantity', models.IntegerField(null=True)),
                ('barcode', models.CharField(max_length=255, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('color', models.CharField(max_length=255, null=True)),
                ('is_tracking', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('on_offer', models.BooleanField(default=False)),
                ('featured_until', models.DateField(null=True)),
                ('mnf_date', models.DateField(null=True, verbose_name='Manufactured date')),
                ('exp_date', models.DateField(null=True, verbose_name='Expiry date')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['name'],
                'default_related_name': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('stock_quantity', models.IntegerField(null=True)),
                ('barcode', models.CharField(max_length=255, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('color', models.CharField(max_length=255, null=True)),
                ('is_tracking', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('on_offer', models.BooleanField(default=False)),
                ('featured_until', models.DateField(null=True)),
                ('mnf_date', models.DateField(null=True, verbose_name='Manufactured date')),
                ('exp_date', models.DateField(null=True, verbose_name='Expiry date')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'product variant',
                'verbose_name_plural': 'product variants',
                'ordering': ['name'],
                'default_related_name': 'product_variants',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, null=True, verbose_name='url image')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ['-date_created'],
                'default_related_name': 'product_images',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'rating'], name='products_pr_name_b30300_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['name', 'rating'], name='products_pr_name_6dc13c_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['id', 'is_deleted'], name='products_pr_id_2f20c4_idx'),
        ),
    ]
