# Generated by Django 4.1.7 on 2023-04-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_products_pr_name_b30300_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured_until',
        ),
        migrations.RemoveField(
            model_name='product',
            name='on_offer',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='featured_until',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='on_offer',
        ),
    ]
