# Generated by Django 4.1.7 on 2023-04-21 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('brands', '0001_initial'),
        ('products', '0003_remove_product_featured_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='brands.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.business'),
        ),
    ]
